---
- hosts: rev_proxy_a
  remote_user: vagrant

  tasks:
      - name: 'add nginx pgp key'
        become: true
        apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present

      - name: 'add nginx repository'
        become: true
        apt_repository:
            repo: deb http://nginx.org/packages/ubuntu/ bionic nginx

      - name: 'apt update'
        become: true
        apt:
            update_cache: true

      - name: 'install nginx'
        become: true
        apt:
            name: nginx
            state: latest

      - name: 'enable and start nginx'
        become: true
        systemd:
            name: nginx
            enabled: true
            state: started

      - name: 'scp nginx conf'
        copy:
            src: /Users/atsushikonishi/WorkSpace/Infra/infra_practice/task01/nginx/rev_proxy_a.conf
            dest: /home/vagrant/nginx/
            force: true

      - name: 'scp ssl keys'
        become: true
        copy:
            src: /Users/atsushikonishi/WorkSpace/Infra/infra_practice/task01/keys
            dest: /home/vagrant/
            directory_mode: true
            mode: 644
            owner: vagrant
            group: vagrant
            force: true

      - name: 'restart nginx'
        become: true
        systemd:
            name: nginx
            state: restarted

