---
- hosts: vagrants
  remote_user: vagrant
  tasks:
    - name: add nginx gpg key
      sudo: true
      apt_key:
          url: https://nginx.org/keys/nginx_signing.key
          state: present
    - name: add nginx repository
      apt_repository:
          repo: deb http://nginx.org/packages/ubuntu/ bionic nginx
    - name: apt update
      apt:
          update_cache: yes
    - name: install nginx
      sudo: true
      apt:
          name: nginx

