---
- hosts: web_a
  remote_user: vagrant
  vars:
      rbenv_root: /usr/local/rbenv/

  tasks:
      - name: 'add nginx pgp key'
        become: true
        apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            state: present

      - name: 'add nginx repository'
        become: true
        apt_repository:
            repo: deb http://nginx.org/packages/ubuntu/ bionic nginx

      - name: 'apt update'
        become: true
        apt:
            update_cache: true

      - name: 'install nginx'
        become: true
        apt:
            name: nginx
            state: latest

      - name: 'scp nginx conf'
        copy:
            src: /Users/atsushikonishi/WorkSpace/Infra/infra_practice/task01/nginx
            dest: /home/vagrant/
            force: true

      - name: 'scp html'
        copy:
            src: /Users/atsushikonishi/WorkSpace/Infra/infra_practice/task01/html
            dest: /home/vagrant/
            force: true

      - name: 'restart nginx'
        become: true
        systemd:
            name: nginx
            enabled: true
            state: restarted

      - name: 'install pkg for ruby dependencies'
        become: true
        apt:
            update_cache: true
            name:
            - autoconf
            - bison
            - build-essential
            - libssl-dev
            - libyaml-dev
            - libreadline6-dev
            - zlib1g-dev
            - libncurses5-dev
            - libffi-dev
            - libgdbm5
            - libgdbm-dev

      - name: 'install rbenv'
        become: true
        git:
            repo: https://github.com/rbenv/rbenv.git
            dest: "{{ rbenv_root }}"

      - name: 'install ruby-build'
        become: true
        git:
            repo: https://github.com/rbenv/ruby-build.git
            dest: "{{ rbenv_root }}plugins/ruby-build/"

      - name: 'send rbenv.sh to /etc/profile.d'
        become: true
        template:
            src: profile.d/rbenv.sh.j2
            dest: /etc/profile.d/rbenv.sh
            owner: vagrant
            group: vagrant
            mode: 0755

      - name: 'change group rbenv'
        become: true
        file:
            path: "{{ rbenv_root }}"
            owner: vagrant
            group: vagrant
            recurse: true
            state: directory

      - name: 'install ruby 2.6.5'
        shell: bash -lc "rbenv install --skip-existing 2.6.5"

      - name: 'set ruby version 2.6.5'
        shell: bash -lc "rbenv global 2.6.5"

      - name: 'install old node'
        become: true
        apt:
            pkg:
            - nodejs
            - npm

      - name: 'install n'
        become: true
        shell: npm install -g n

      - name: 'install node 13.11.0'
        become: true
        shell: n install 13.11.0

      - name: 'purge old node'
        apt:
            name:
            - nodejs
            - npm
            purge: true

      - name: 'install node yarn'
        shell: echo "skip install node"
